### ISSUE TITLE
compose

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-addons#15]
```js
set('state://module/path', compose({
  foo: 'input:/bar',
  bar: 'input:/baz'
})
```

**Comment by garth** [comment]
This is supported today, though not with set.

```js
copy(compose({
  foo: 'input:/bar',
  bar: 'input:/baz'
}), 'state://module/path)
```

Is there a better name than `compose`?

Perhaps we could have `structure` and later `destructure`?

**Comment by Guria** [comment]
I have no suggestions on better naming. Let ask @christianalfoni

**Comment by garth** [comment]
with structure/destructure:

```js
copy(structure({
  foo: 'input:/bar',
  bar: 'state:/foo'
}), destructure({
  foo: 'output:/foo',
  bar: 'state:/bar'
}))
```

My only concern is that this is currently possible with existing factories, your example could be done like this:

```js
copy('input:/bar', 'state://module/path/foo')
copy('input:/baz', 'state://module/path/bar')
``

Which is arguably more readable?

**Comment by Guria** [comment]
yeap, it's true for `copy`.
But I thought about passing params to `services://` or `redirect://`. It can't be splitted in such way.

**Comment by garth** [comment]
You can copy multiple times to output which would work to prepare service input

**Comment by Guria** [comment]
Hmm. Seems reasonable. Can we output to undefined path in output? `copy('42', 'output:deep.not.exists')`

**Comment by garth** [comment]
Yes

**Comment by Guria** [comment]
Cool
