### ISSUE TITLE
change compliler to regular deps

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-addons#16]
I would propose to move `cerebral-url-scheme-compiler` as regular deps since npm@3 doesn't installs peerDependencies. On the other hand `npm@3` will use only one copy of `cerebral-url-scheme-compiler` if all modules using it have compatible version range.

peerDependencies supposed to [declare some limitations to modules not required in main sources (not tests)](https://github.com/cerebral/cerebral-module-devtools/blob/master/package.json#L35-L37) or declare that loading of separate instance of module should be avoided (like when we do `require('react')`)

**Comment by garth** [comment]
@Guria yes, I was thinking about this.I wasn't sure that other modules were going to depend on schema compiler and how each would be affected.

**Comment by Guria** [comment]
Let each depend it just as regular. Having `cerebral-url-scheme-compiler` in app deps would be to annoying.
