### ISSUE TITLE
filter

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral-addons#17]
Similar to copy `filter` would allow a value to be modified as it is being copied:

```js
filter('input:/email', toLower, 'state:/email')
```

A filter function must be provided which accepts an input value and returns an output value.

eg:

```js
const toLower = str => str.toLowerCase()
```

**Comment by Guria** [comment]
I would suggest to place filter function as 3rd argument:
```js
filter('input:/email', 'state:/email', (val) => {
  return //...
})
```

**Comment by Guria** [comment]
Even better is just make it part of `copy`:
```js
copy('input:/email', 'state:/email', (val) => {
  return //...
})
```

**Comment by garth** [comment]
@Guria just added output chains for copy which gives much more power/flexibility
