### ISSUE TITLE
statePath substitution from input

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-addons#2]
Would be great to allow substitutions in all factories that accepts `statePath`:
`set(['tasks', ':taskId', results, ':resultIndex', '$someFlag'], true)`

We can escape colon with another colon to allow path part start with colon :)

**Comment by garth** [comment]
I have been thinking about this and I like the idea of enabling it across all methods that take a state path via a shared implementation.

`:id` also seems like a good idea as it's then common with the routing definition.

The bit that I think needs a little more thought is where the values for `:x` come from. I don't yet have a real world app that needs this to play with, but hopefully I'll get there soon.

At the moment I'm thinking along the lines we may need two options, 1 where the values comes from the store and 2 where the value comes from the input. So for example, when working with routes the router will give you a hash of prams which you can put into the store, if the factory methods know the location of the router params in the store then they can fetch from there. If there is a similar params property on the input that could override what is in the store.

Alternatively we could use a syntax within the  `':'` part of the path that we can parse to know where to get the value from. So `':store/route/params/id'` could take the current id from the route params in the store and `:input/params/id` could take the id from `{ params: { id: 1 } }` from the action input.

It may be possible to combine both options and have something like this:

* `set(statePath, value, { routerParamsPath=['route', 'params'] })`

```js
// default to check for id in input params, falling back to the router params
set(['tasks', ':id', 'prop'], true);

// specific where the params come from
set(['tasks', ':id', 'prop'], true, {
  id: 'store/currentTaskId'
});
```

**Comment by christianalfoni** [comment]
Just giving a couple of cents here :-)

It is really interesting to see how this evolves and I think there are really great ideas here! Though I also think it is important to keep a balance in mind, a balance between the flow abstraction and implementation details. If these factories gets too many parameters, you could basically just write:

```js
signal('somethingHappened', (input, state) => (state.set(['somePath', input.id], true)); 
```
You have to read all the details to understand what it is doing, as:
```js
signal('somethingHappened', setTaskPropByParamId); 
```
just says exactly what id does, you do not really have to build a mental image for it. 

So this is not saying that anything is bad here, just pointing out that there is a balance here. This balance is probably different for different teams/devs, but it definitely is there :)

**Comment by garth** [comment]
I think that we have managed without this for long enough to close the issue
