### ISSUE TITLE
pop.js gets blocked by uBlock Origin

### ISSUE THREAD

**Issue by NervosaX** [cerebral/cerebral-addons#22]
https://github.com/cerebral/cerebral-addons/blob/master/pop.js

This is a really weird one! I was getting weird failures in cerebral addons on this request:

system.src.js:5002 GET http://localhost:6533/jspm_packages/npm/cerebral-addons@0.5.3/pop.js net::ERR_BLOCKED_BY_CLIENT

Turns out, uBlock Origin is blocking it. Perhaps pop (popup) is a targeted word for blocking. 

Maybe the name should be changed? The fix was obviously to disable adblock for localhost.

**Comment by christianalfoni** [comment]
Haha, crazy stuff! Though should be possible to whitelist localhost or something?

**Comment by garth** [comment]
I don't suppose that this would be an issue in production when you have packaged everything?

**Comment by christianalfoni** [comment]
@garth Nopes, you are right, as long as you do not call your dist bundle `pop.js` :D

**Comment by garth** [comment]
Maybe we should add a note to the readme?
