### ISSUE TITLE
Truncate getter/setter

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral-addons#23]
How would you feel about having a truncate getter and/or setter that truncates a string to N characters?

```javascript
copy('input:/myString', truncate('state:/myString', 10))
copy(truncate('input:/myString', 10), 'state:/myString')
```

**Comment by garth** [comment]
you can create your own getters. Did you try this? https://github.com/cerebral/cerebral-addons#getters

**Comment by maxfrigge** [comment]
Nope haven't tried it yet, because I wanted it to support passing dynamic data too. The getter and setter samples seem to be dealing with static data only.

**Comment by garth** [comment]
Isn't all the data dynamic? Your sample truncate function would look something like this:

```js
import getCompiler from 'cerebral-url-scheme-compiler/get'

export default function (path, length) {
  const getter = getCompiler(path)

  return function truncate(args) => {
    return getter(args).truncate(length)
  }
}
```

**Comment by maxfrigge** [comment]
Will give it a shot. Thanks!

So the idea is to create your own getter/setter rather then adding more to the addons?

**Comment by garth** [comment]
We probably can't account of all possibilities, so we created the getCompiler so that you can reuse those parts for your own custom getters/setters.

If there is enough interest in `truncate` or similar then of course we can put it into addons and make it available to everyone.

**Comment by maxfrigge** [comment]
Got it :)
