### ISSUE TITLE
[Request Functionality in "copy" factory method]  Setting State for specific module.

### ISSUE THREAD

**Issue by SheikhG1900** [cerebral/cerebral-addons#24]
It would be better if **copy** factory method allows to set module state . Having this functionality, we can define our signal chains more generically. 

From Cerebral boilerplate sample code, in file **modules\Example\signals\colorChanged.js** following signal chain is defined. Here text **example** is taken from our application configuration, defined in **main.js**. 
```
[
  copy('input:/color', 'state:/example.color')
];
```
It would be more generic if we can use copy method one of following ways.

```
[
  copy('input:/color', 'module.state:/color')  //the state object, defined in module object {module:{state},modules,state}
];
```

```
[
  copy('input:/color', 'state:/color', {useModule:true}) //taking an option argument.
];
```

**Comment by garth** [comment]
We already have this.

The syntax is `state://module/color`.

Though there is a possibility that this may change with recent changes to cerebral modules.

//cc @christianalfoni

**Comment by SheikhG1900** [comment]
that's great.

**Comment by SheikhG1900** [comment]
This syntax is not working. Is there any documentation for these factory methods so I can figure out the issue.

**Comment by christianalfoni** [comment]
Sorry about missing documentation @SheikhG1900 , we are working on new website as we speak. It will be released early July. The latest version of Cerebral does not include modules. We made a choice to remove them and make modules architecture a choice. You can install the `cerebral-provider-modules` which gives you modules and the `module` syntax should work again. This is a recent change, have you used `module` syntax with latest 0.34 @garth ?

**Comment by garth** [comment]
I have recently finished up a project which was kept on 0.33 due to the risk associated with the changes in 0.34. So not spent a lot of time with 0.34 yet.

**Comment by christianalfoni** [comment]
Just closing this is `cerebral-provider-modules` is the package to use to allow modules in actions :)
