### ISSUE TITLE
specify property path using dot notation string instead of array of strings

### ISSUE THREAD

**Issue by TomKaltz** [cerebral/cerebral-addons#5]
https://github.com/deoxxa/dotty or something like it?

**Comment by christianalfoni** [comment]
This is a good idea. So you can choose the signature `state.get('foo.bar')` or `state.get(['foo', 'bar'])`. Let me just get some more thoughts on this.

**Comment by TomKaltz** [comment]
I also submitted this to Baobab

https://github.com/Yomguithereal/baobab/issues/415

**Comment by christianalfoni** [comment]
Will have to think about it some more. It does help readability, so just have to make sure it does not affect other things too much

**Comment by Pavel910** [comment]
+1 on this! That's one of the main reasons I use lodash, because of the dot notation support on get/set methods. Maybe it could be enabled as a configuration parameter? That way people will have to turn it on and be aware of consequences it implies.

**Comment by garth** [comment]
@christianalfoni u guess this is something that would need to be enabled on cerebral rather than addons?

**Comment by Pavel910** [comment]
@garth I came here following Baobab issue, and I was actually referring to Baobab dot notation, thought it is related. @TomKaltz submitted it to Baobab so if you ever implement it, please consider Baobab as well.

**Comment by christianalfoni** [comment]
Yeah, we can put this in cerebral, as it registers all the accessors. Can just convert string to array using `split`. I do not see any reason why we can not do it, even though Falcor and others disapprove it. It is a matter of taste I think.

**Comment by christianalfoni** [comment]
Okay, this will be part of next version

**Comment by garth** [comment]
This has now been solved by a combination of changes in cerebral and the latest addons
