### ISSUE TITLE
remove autogenerated content

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-addons#6]
just add `lib` to `.gitignore` and use `.npmignore`
>Use a .npmignore file to keep stuff out of your package. If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it. Like git, npm looks for .npmignore and .gitignore files in all subdirectories of your package, not only the root directory.

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by garth** [comment]
I believe you can also use the `files` attribute of the package file which might be better.
