### ISSUE TITLE
introduce scoped option for factories

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-addons#7]
Since we have great scoped modules in `cerebral@0.29` would be great to support it in addons.

Proposal: `set(statePath, value, scoped)`
Example: `set(['filter'], 'active', true)` would do `module.state.set(['filter'], 'active')` internally.

**Comment by Guria** [comment]
Also referencing other modules by its alias name would be useful.

**Comment by christianalfoni** [comment]
I thought about this a bit actually. And I think it would be better to expose own addons for modules. So you would:

```js
moduleSet(statePath, value);
set(statePath, value)
```

It is more expressive. I see the point of it not being as dry, but I think expressiveness wins here. Just my opinion though :-)

**Comment by Guria** [comment]
@christianalfoni what about accessing other modules state?

**Comment by christianalfoni** [comment]
I have a feeling that an action factory convention will be to pass in the name of the module as the first argument. So in that case:

```js
moduleSet(statePath, value) // Current module
moduleSet('someModule', statePath, value) // Specific module
```

**Comment by christianalfoni** [comment]
It follows the convention suggested of shared modules, at the bottom: http://www.cerebraljs.com/modules

**Comment by garth** [comment]
Just throwing out another idea:

```js
controller.signal('somethingHappened', [

  // actions get given a { module } arg which defaults the module that the signal is on (no change)
  set(['someKey'], 'value'),

  // change the { module } arg to point to another module (applies to all contained actions)
  changeModule('cerebral-module-x', [
    // value is now set on the changed module.
    set(['someKey'], 'value'),
    // do other actions on cerebral-module-x
  ]),

  // back on the default module again
  set(['otherKey'], true)
]);
```

So as an action author I can just code actions that only need to worry about the { module } arg, but can be used to apply to any module.

`changeModule` could possibly be just another action provided by cerebral-addons.

**Comment by garth** [comment]
Final idea for the day (just came to me in the shower so it must be good :smile: ):

```js
// set a value on the current module
module(set, path(['someKey']), 'value')

// set a value on another module
module('cerebral-module-x', set, path(['someKey']), 'value')

// set a global value (unchanged)
set(['someKey'], 'value');
```

The `module()` action will wrap the given action function an insert the module namespace to `path()` params allowing existing actions to remain unchanged.

We could optionally drop the `module()` wrapper and renamed `path` from the above to `module` but then the actions would have to change slightly:

```js
// set a value on the current module
set(module(['someKey']), 'value')

// set a value on another module
set(module('cerebral-module-x', ['someKey']), 'value')

// set a global value (unchanged)
set(['someKey'], 'value');
```

**Comment by christianalfoni** [comment]
Ah, composition is always welcome! :) I definitely think that makes sense!

**Comment by christianalfoni** [comment]
I think I like the second one best actually. It composes better

**Comment by maxfrigge** [comment]
I think you would have to try it out.. but just from reading the issue I would say that the readability suffers too much. 

I am not up to date with the specs, but since module state is just a branch of global state why couldn't you just use it as `set(['module', 'someKey'], 'value')`?

**Comment by christianalfoni** [comment]
You can do that too @maxfrigge :)

**Comment by christianalfoni** [comment]
Though I see your point on the second example... its no difference really

**Comment by garth** [comment]
ok, so with the second one we well also add a helper that can be used inside the action:

```js
// the signal
[
  set(module('moduleName', ['statePath']), 'value')
]

// inside the action
function (statePath, value) {
  return function set({ module, modules, state }) {
    const resolve = pathResolver(modules, module);
    state.set(resolve(statepath), value);
  };
}
```

**Comment by garth** [comment]
The only issue is that the signals don't know what the module is called, but the actions do, so you need to defer the decision.

**Comment by garth** [comment]
you could have the first item in the path being '.' or '/' or 'modulename'?

**Comment by maxfrigge** [comment]
No quite getting the benefit of this? Is it to support aliases that differ from a modules actual namespace? Or are there other things that come with it?

**Comment by garth** [comment]
or it could be done via an object perhaps:

```js
set({ someModule: [statePath]}, 'value')
```

**Comment by maxfrigge** [comment]
Looks cleaner to me than the functional approach .. and you could set multiple properties with one stone.

**Comment by garth** [comment]
@maxfrigge, the idea is to have the same relative, global or specific module namespacing in shared actions as we have in other places.

**Comment by garth** [comment]
```js
set({
  '/': ['statePath'],  // global
  '.': ['statePath'],  // current module
  someModule: ['statePath'], // specific module
}, 'value')
```

**Comment by garth** [comment]
Not sure if I like it...

**Comment by maxfrigge** [comment]
Maybe use the functional approach but leave the state path out of it. `module()` could return an object that identifies it as a module directive.. if a plain old string could collide.

```javascript
set(
  module('my-module'),
  ['path', 'to', 'prop'],
  value
)

set(
  module('.'),
  ['path', 'to', 'prop'],
  value
)

set(
  module('/'),
  ['path', 'to', 'prop'],
  value
)
```
To me it was just strange to have the module definition wrap the state path.

I think not having any special syntax should always reference the current module and you would only add  syntax to either access another module or root.

**Comment by garth** [comment]
@maxfrigge, `set` is only one example. There are other action methods which may require one more path params, so wrapping the param in `module` allows greater flexibility.

**Comment by maxfrigge** [comment]
Ok. Got it. But currently only statePaths are scoped.. right?

**Comment by garth** [comment]
yes.

I just want to avoid having to maintain 3 different versions of each addon action.

**Comment by maxfrigge** [comment]
Who would :)

What about going back to @Guria original proposal and add an optional parameter that sets the scope - maybe use s string for greater options: module-name, global, local (deafault).

Guess it would be a good starting point and wouldn't diverge much from the current signatures. Then people could start using it and time will tell if it gets adopted or not.

**Comment by garth** [comment]
What happens when you want to move a value from one module to another? I think that we need something more flexible.

**Comment by garth** [comment]
I think that this has been resolved in the latest release
