### ISSUE TITLE
Split when into whenState and whenInput

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral-addons#8]
Would be really helpful to be able to check on input too when using when - so I suggest to split it up into whenState (the current when) and whenInput (new when).

**Comment by garth** [comment]
Sounds like a good idea. Maybe it should only check input. Then you can do stateToOutput first?

**Comment by maxfrigge** [comment]
I haven't yet made up my mind whether actions should operate on input or state and if it would make sense to have one way of doing or if it should always be up to the developer.

Some more opinions would good for this one.

**Comment by maxfrigge** [comment]
Take this use case

```javascript
import setError from '../actions/setError'
import submitOrder from '../actions/submitOrder'
import setState from '../actions/setState'
import validateOrder from '../actions/validateOrder'
import redirectToUrl from '../actions/redirectToUrl'
import { when } from 'cerebral-addons'

const whenOrderIsValid = when(['checkout', 'orderForm', 'valid'], { valid: when.truthy })

const orderSubmitted = [
  validateOrder,
  whenOrderIsValid, {
    valid: [
      setState(['checkout', 'orderForm', 'loading'], true),
      [
        submitOrder, {
          success: [
            redirectToUrl('/thankyou')
          ],
          error: [
            setError,
            setState(['checkout', 'orderForm', 'loading'], false)
          ]
        }
      ]
    ]
  }
]

export default orderSubmitted
```

The action `whenOrderIsValid` throws an error on [this line](https://github.com/cerebral/cerebral-addons/blob/master/src/factories/when.js#L27) because the otherwise output doesn't exist.

**Comment by garth** [comment]
By switching to input we make it more compossible. So it's then the choice of the developer without addons having to implement multiple versions.

**Comment by maxfrigge** [comment]
Agree. I am a bit in between though whether it's to cumbersome to always copy state to input or whether it could become some sort of best practice to have actions work on input/output and do the state transition in a separate action.

**Comment by garth** [comment]
Humm. This is feeling similar to the module path discussion. Maybe some kind of path syntax that allows you to define the base (module, global, input, etc)

**Comment by maxfrigge** [comment]
Good point. Always hard to decide without using it for a while.

**Comment by garth** [comment]
I was toying with the idea of url scheme:
```
scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]
```
where only scheme and path are mandatory.

So scheme could be used for (state|input), host could be used for (module) and path could be used as we currently do with statePath.

//cc @christianalfoni @Guria

**Comment by Guria** [comment]
Very interesting

**Comment by garth** [comment]
So to reference and input value you would do:
```
input:key.subkey
```
to reference global state
```
state:key.subkey
```
to reference module state
```
state://moduleName/key.subkey
```

**Comment by Guria** [comment]
Maybe try it in a branch?

**Comment by garth** [comment]
+ there are already good url parsers, so you don't need to write one.

**Comment by Guria** [comment]
"host" part would be meaningless for `input` "scheme"?

**Comment by garth** [comment]
yes, but host is optional according to url spec.

I will make a mockup in addons

**Comment by Guria** [comment]
Got it. Optional but still meaningfull. Still worth to try.

**Comment by garth** [comment]
This has been solved by the latest release.
