### ISSUE TITLE
Make outputs optional on when addon

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral-addons#9]
Currently it's required to define both truthy and falsy/otherwise outputs. Why not make them optional so you can define scenarios where only one outcome ends in an action and the other does nothing?

**Comment by garth** [comment]
@maxfrigge could you provide some example code?

**Comment by maxfrigge** [comment]
Take this use case

```javascript
import setError from '../actions/setError'
import submitOrder from '../actions/submitOrder'
import setState from '../actions/setState'
import validateOrder from '../actions/validateOrder'
import redirectToUrl from '../actions/redirectToUrl'
import { when } from 'cerebral-addons'

const whenOrderIsValid = when(['checkout', 'orderForm', 'valid'], { valid: when.truthy })

const orderSubmitted = [
  validateOrder,
  whenOrderIsValid, {
    valid: [
      setState(['checkout', 'orderForm', 'loading'], true),
      [
        submitOrder, {
          success: [
            redirectToUrl('/thankyou')
          ],
          error: [
            setError,
            setState(['checkout', 'orderForm', 'loading'], false)
          ]
        }
      ]
    ]
  }
]

export default orderSubmitted
```

The action `whenOrderIsValid` throws an error on [this line](https://github.com/cerebral/cerebral-addons/blob/master/src/factories/when.js#L27) because the otherwise output doesn't exist.

**Comment by garth** [comment]
I kind of like having all paths explicit. When you read this, I wonder what happens when the order is invalid?

**Comment by maxfrigge** [comment]
Well nothing happens, because the validation updates the form state which updates the ui.

I get you point thought that it could be avoided by design .. but it would still be nice to have the option :)

**Comment by maxfrigge** [comment]
Here is another use case where it don't see any reason to specify any other path then isTrue - if you decide to make that call inside the signal.

```javascript
import whenFieldName from '../actions/whenFieldName'
import updateOrder from '../actions/updateOrder'
import validateOrderField from '../actions/validateOrderField'

const orderFieldChanged = [
  updateOrder,
  whenFieldName('acceptTerms'), {
    isTrue: [validateOrderField]
  }
]

export default orderFieldChanged
```

**Comment by garth** [comment]
Don't you think that adding the `isFalse` condition clarifies what will happen when it's not true?

```js
whenFieldName('acceptTerms'), {
  isTrue: [validateOrderField],
  isFalse: []
}
```

In every app I have I do something in the isFalse path like this

```js
whenFieldName('acceptTerms'), {
  isTrue: [validateOrderField],
  isFalse: [showSnackbarMessage('Please accept the terms')]
}
```

**Comment by maxfrigge** [comment]
My case is not about validation. I have a change and a blur signal for all form fields. All text inputs validate on blur, but the checkbox should validate on change too. 

Well .. it doesn't really hurt to have those empty paths defined so I will close for now and get back in case I can't take it anymore :-)
